--------------------------------------------------------
--  File created - Thursday-September-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BREAKDOWN
--------------------------------------------------------

  CREATE TABLE "APPS"."BREAKDOWN" 
   (	"EQUIPMENTID" NCHAR(8), 
	"FROMTIME" TIMESTAMP (6), 
	"TOTIME" TIMESTAMP (6), 
	"WORKORDER" NUMBER(10,0), 
	"BDNREASON" NCHAR(300), 
	"BREAKDOWNID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE , 
	"BDNTOTALTIME" NUMBER(*,0) GENERATED ALWAYS AS (EXTRACT(DAY FROM ("TOTIME"-"FROMTIME")DAY(9) TO SECOND(2))*24*60*60+EXTRACT(HOUR FROM ("TOTIME"-"FROMTIME")DAY(9) TO SECOND(2))*60*60+EXTRACT(MINUTE FROM ("TOTIME"-"FROMTIME")DAY(9) TO SECOND(2))*60+EXTRACT(SECOND FROM ("TOTIME"-"FROMTIME")DAY(9) TO SECOND(2))) VIRTUAL 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table COMPONENT
--------------------------------------------------------

  CREATE TABLE "APPS"."COMPONENT" 
   (	"COMPONENTSN" NCHAR(25), 
	"COMPONENTPARTCODE" NCHAR(20), 
	"COMPONENTSTATUS" NCHAR(15), 
	"COMPONENTEQUIPMENT" NCHAR(8), 
	"COMPONENTMANFACTURER" NCHAR(15), 
	"COMPONENTMODEL" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table COMPONENTSTATUS
--------------------------------------------------------

  CREATE TABLE "APPS"."COMPONENTSTATUS" 
   (	"COMPONENTSTATUS" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table EQUIPMENT
--------------------------------------------------------

  CREATE TABLE "APPS"."EQUIPMENT" 
   (	"EQUIPMENTID" NCHAR(8), 
	"EQUIPMENTFAMILYID" NCHAR(5), 
	"EQUIPMENTSN" NCHAR(50), 
	"EQUIPMENTHR" NUMBER(10,0), 
	"EQUIPMENTHRDATE" DATE, 
	"EQUIPMENTSTATUSID" NCHAR(5), 
	"INSERVICEDATE" DATE, 
	"EQUIPMENTMANUFACTURER" NCHAR(20), 
	"EQUIPMENTCAPACITY" NUMBER, 
	"EQUIPMENTBATCH" NCHAR(1), 
	"REFUELED" NUMBER, 
	"EQUIPMENTMODEL" NCHAR(20), 
	"EQUIPMENTDIRECTIVE" NCHAR(200), 
	"WARRANTYENDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table EQUIPMENTFAMILY
--------------------------------------------------------

  CREATE TABLE "APPS"."EQUIPMENTFAMILY" 
   (	"EQUIPMENTFAMILYCODE" NCHAR(5), 
	"EQUIPMENTTYPEDIRECTIVE" NCHAR(50), 
	"EQUIPMENTSCOPE" NCHAR(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table EQUIPMENTSTATUS
--------------------------------------------------------

  CREATE TABLE "APPS"."EQUIPMENTSTATUS" 
   (	"EQUIPMENTSTATUSID" NCHAR(5), 
	"EQUIPMENTSTATUSDIRECTIVE" NCHAR(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table EQUIPMENTTYPE
--------------------------------------------------------

  CREATE TABLE "APPS"."EQUIPMENTTYPE" 
   (	"EQUIPMENTTYPEID" NCHAR(3), 
	"COUNT" NUMBER(10,0), 
	"EQUIPMENTTYPEDIRECTIVE" NCHAR(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table FUELINGWORKORDER
--------------------------------------------------------

  CREATE TABLE "APPS"."FUELINGWORKORDER" 
   (	"FUELINGWORKORDER" NUMBER(10,0), 
	"EQUIPMENTID" NCHAR(8), 
	"FUELQTY" NUMBER(10,0), 
	"EQUIPMENTREADING" NUMBER(10,0), 
	"FUELINGDATE" TIMESTAMP (3), 
	"COMMENTS" NCHAR(200), 
	"UOM" NCHAR(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table ISSUE
--------------------------------------------------------

  CREATE TABLE "APPS"."ISSUE" 
   (	"WORKORDER" NUMBER(10,0), 
	"QTY" NUMBER(10,0), 
	"SPAREPARTCODE" NCHAR(20), 
	"ISSUEDATE" DATE, 
	"PARTPRICE" NUMBER, 
	"TOTALPRICE" NUMBER(*,2) GENERATED ALWAYS AS ("QTY"*"PARTPRICE") VIRTUAL , 
	"REQUESTDATE" DATE, 
	"ISSUESTATE" NCHAR(15), 
	"ISSUEID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE , 
	"REQUESTERID" NCHAR(10), 
	"ISSUERID" NCHAR(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table ISSUESTATUS
--------------------------------------------------------

  CREATE TABLE "APPS"."ISSUESTATUS" 
   (	"ISSUESTATUS" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table ODP_USER
--------------------------------------------------------

  CREATE TABLE "APPS"."ODP_USER" 
   (	"USERNAME" NCHAR(20), 
	"USERID" NCHAR(10), 
	"USERPASSWORD" NCHAR(15), 
	"USERTITLE" NCHAR(25), 
	"USERIMAGE" BLOB, 
	"USEREMAIL" NCHAR(30), 
	"USERIDNUMBER" NUMBER(10,0), 
	"USERLEVEL" NCHAR(10), 
	"USERSECTION" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 
 LOB ("USERIMAGE") STORE AS SECUREFILE (
  TABLESPACE "APPS_TS_TX_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PMTEMPLATE
--------------------------------------------------------

  CREATE TABLE "APPS"."PMTEMPLATE" 
   (	"EQUIPMENTFAMILY" NCHAR(5), 
	"PMDIRECTIVE" NVARCHAR2(100), 
	"PMATTACHMENT" BLOB, 
	"PMISSUES" NUMBER(10,0), 
	"PMSN" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" 
 LOB ("PMATTACHMENT") STORE AS SECUREFILE (
  TABLESPACE "APPS_TS_TX_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SPAREPART
--------------------------------------------------------

  CREATE TABLE "APPS"."SPAREPART" 
   (	"PARTCODE" NCHAR(20), 
	"MANUFACTURERPN" NCHAR(20), 
	"PARTDIRECTIVE" NVARCHAR2(50), 
	"PARTPRICE" NUMBER, 
	"PARTSTOCKQTY" NUMBER(10,0), 
	"COMPATABLEEQUIPMENTFAMILYID" NCHAR(5), 
	"SUPPLIERID" NCHAR(10), 
	"RESERVEDSTOCK" NUMBER(10,0), 
	"AVAILABLESTOCK" NUMBER GENERATED ALWAYS AS ("PARTSTOCKQTY"-"RESERVEDSTOCK") VIRTUAL , 
	"UOM" NCHAR(4), 
	"OEM_PN" NCHAR(50), 
	"OPM_PN" NCHAR(50), 
	"LOCATION" NCHAR(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table STORERETURN
--------------------------------------------------------

  CREATE TABLE "APPS"."STORERETURN" 
   (	"WORKORDER" NUMBER(10,0), 
	"QTY" NUMBER(10,0), 
	"COMPONENTSN" NCHAR(25), 
	"RETURNPRICE" NUMBER, 
	"RETURNID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table UOM
--------------------------------------------------------

  CREATE TABLE "APPS"."UOM" 
   (	"UOMID" NCHAR(4), 
	"UOMDESCRIPTION" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table USERLEVEL
--------------------------------------------------------

  CREATE TABLE "APPS"."USERLEVEL" 
   (	"USERLEVEL" NCHAR(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table USERSECTION
--------------------------------------------------------

  CREATE TABLE "APPS"."USERSECTION" 
   (	"USERSECTION" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table WORKDONETYPES
--------------------------------------------------------

  CREATE TABLE "APPS"."WORKDONETYPES" 
   (	"WORKDONETYPEID" NCHAR(3), 
	"WORKDONETYPEDIRECTIVE" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table WORKORDER
--------------------------------------------------------

  CREATE TABLE "APPS"."WORKORDER" 
   (	"WORKORDERDIRECTIVE" NVARCHAR2(100), 
	"WORKORDERSTATUSID" NCHAR(15), 
	"WORKORDERTYPEID" NCHAR(3), 
	"WORKSTARTDATE" TIMESTAMP (6), 
	"WORKDONEDATE" TIMESTAMP (6), 
	"WORKORDEREQUIPMENTID" NCHAR(8), 
	"WORKORDERCREATORID" NCHAR(10), 
	"WORKORDERREGISTERATIONDATE" TIMESTAMP (6), 
	"WORKORDERFINISHDATE" TIMESTAMP (6), 
	"WORKORDERNOTES" NCLOB, 
	"EQUIPMENTRH" NUMBER(10,0), 
	"WORKDONETYPE" NCHAR(3), 
	"WORKORDERATTACH" BLOB, 
	"WORKORDERID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 48 NOCACHE  NOORDER  NOCYCLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 
 LOB ("WORKORDERNOTES") STORE AS SECUREFILE (
  TABLESPACE "APPS_TS_TX_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("WORKORDERATTACH") STORE AS SECUREFILE (
  TABLESPACE "APPS_TS_TX_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table WORKORDERSTATUS
--------------------------------------------------------

  CREATE TABLE "APPS"."WORKORDERSTATUS" 
   (	"WORKORDERSTATUSID" NCHAR(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table WORKORDERTYPE
--------------------------------------------------------

  CREATE TABLE "APPS"."WORKORDERTYPE" 
   (	"WORKORDERTYPEDIRECTIVE" NCHAR(30), 
	"WORKORDERTYPEID" NCHAR(3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index BREAKDOWN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."BREAKDOWN_PK" ON "APPS"."BREAKDOWN" ("BREAKDOWNID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_COMPONENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_COMPONENT" ON "APPS"."COMPONENT" ("COMPONENTSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_COMPONENTSTATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_COMPONENTSTATUS" ON "APPS"."COMPONENTSTATUS" ("COMPONENTSTATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_EQUIPMENT" ON "APPS"."EQUIPMENT" ("EQUIPMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPMENTTYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_EQUIPMENTTYPE" ON "APPS"."EQUIPMENTFAMILY" ("EQUIPMENTFAMILYCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPMENTSTATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_EQUIPMENTSTATUS" ON "APPS"."EQUIPMENTSTATUS" ("EQUIPMENTSTATUSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPMENTTYPE_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_EQUIPMENTTYPE_1" ON "APPS"."EQUIPMENTTYPE" ("EQUIPMENTTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_FUELINGWORKORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_FUELINGWORKORDER" ON "APPS"."FUELINGWORKORDER" ("FUELINGWORKORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index ISSUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."ISSUE_PK" ON "APPS"."ISSUE" ("ISSUEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_ISSUESTATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_ISSUESTATUS" ON "APPS"."ISSUESTATUS" ("ISSUESTATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_USER" ON "APPS"."ODP_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PMTEMPLATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PMTEMPLATE_PK" ON "APPS"."PMTEMPLATE" ("PMSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_SPAREPART
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_SPAREPART" ON "APPS"."SPAREPART" ("PARTCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index STORERETURN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."STORERETURN_PK" ON "APPS"."STORERETURN" ("RETURNID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_UOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_UOM" ON "APPS"."UOM" ("UOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USERLEVEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_USERLEVEL" ON "APPS"."USERLEVEL" ("USERLEVEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_USERSECTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_USERSECTION" ON "APPS"."USERSECTION" ("USERSECTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_WORKDONETYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_WORKDONETYPES" ON "APPS"."WORKDONETYPES" ("WORKDONETYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index WORKORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."WORKORDER_PK" ON "APPS"."WORKORDER" ("WORKORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_WORKORDERSTATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_WORKORDERSTATUS" ON "APPS"."WORKORDERSTATUS" ("WORKORDERSTATUSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_WORKORDERTYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."PK_WORKORDERTYPE" ON "APPS"."WORKORDERTYPE" ("WORKORDERTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Trigger FUELINGWORKORDER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS"."FUELINGWORKORDER_SEQ_TR" 
 BEFORE INSERT ON fuelingWorkOrder FOR EACH ROW
  WHEN (NEW.fuelingWorkOrder IS NULL) BEGIN
 SELECT fuelingWorkOrder_seq.NEXTVAL INTO :NEW.fuelingWorkOrder FROM DUAL;
END;
/
ALTER TRIGGER "APPS"."FUELINGWORKORDER_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table BREAKDOWN
--------------------------------------------------------

  ALTER TABLE "APPS"."BREAKDOWN" MODIFY ("BREAKDOWNID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."BREAKDOWN" ADD CONSTRAINT "BREAKDOWN_PK" PRIMARY KEY ("BREAKDOWNID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
  ALTER TABLE "APPS"."BREAKDOWN" MODIFY ("WORKORDER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."BREAKDOWN" MODIFY ("EQUIPMENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPONENT
--------------------------------------------------------

  ALTER TABLE "APPS"."COMPONENT" MODIFY ("COMPONENTSN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."COMPONENT" ADD CONSTRAINT "PK_COMPONENT" PRIMARY KEY ("COMPONENTSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPONENTSTATUS
--------------------------------------------------------

  ALTER TABLE "APPS"."COMPONENTSTATUS" MODIFY ("COMPONENTSTATUS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."COMPONENTSTATUS" ADD CONSTRAINT "PK_COMPONENTSTATUS" PRIMARY KEY ("COMPONENTSTATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "APPS"."EQUIPMENT" MODIFY ("EQUIPMENTID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENT" MODIFY ("EQUIPMENTFAMILYID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENT" MODIFY ("EQUIPMENTHR" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENT" MODIFY ("EQUIPMENTSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENT" ADD CONSTRAINT "PK_EQUIPMENT" PRIMARY KEY ("EQUIPMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPMENTFAMILY
--------------------------------------------------------

  ALTER TABLE "APPS"."EQUIPMENTFAMILY" MODIFY ("EQUIPMENTFAMILYCODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENTFAMILY" MODIFY ("EQUIPMENTTYPEDIRECTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENTFAMILY" ADD CONSTRAINT "PK_EQUIPMENTTYPE" PRIMARY KEY ("EQUIPMENTFAMILYCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPMENTSTATUS
--------------------------------------------------------

  ALTER TABLE "APPS"."EQUIPMENTSTATUS" MODIFY ("EQUIPMENTSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENTSTATUS" MODIFY ("EQUIPMENTSTATUSDIRECTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENTSTATUS" ADD CONSTRAINT "PK_EQUIPMENTSTATUS" PRIMARY KEY ("EQUIPMENTSTATUSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPMENTTYPE
--------------------------------------------------------

  ALTER TABLE "APPS"."EQUIPMENTTYPE" MODIFY ("EQUIPMENTTYPEID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENTTYPE" MODIFY ("COUNT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENTTYPE" MODIFY ("EQUIPMENTTYPEDIRECTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."EQUIPMENTTYPE" ADD CONSTRAINT "PK_EQUIPMENTTYPE_1" PRIMARY KEY ("EQUIPMENTTYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUELINGWORKORDER
--------------------------------------------------------

  ALTER TABLE "APPS"."FUELINGWORKORDER" MODIFY ("FUELINGWORKORDER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."FUELINGWORKORDER" MODIFY ("FUELQTY" NOT NULL ENABLE);
  ALTER TABLE "APPS"."FUELINGWORKORDER" MODIFY ("FUELINGDATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."FUELINGWORKORDER" ADD CONSTRAINT "PK_FUELINGWORKORDER" PRIMARY KEY ("FUELINGWORKORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE
--------------------------------------------------------

  ALTER TABLE "APPS"."ISSUE" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ISSUE" MODIFY ("SPAREPARTCODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ISSUE" MODIFY ("ISSUEID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ISSUE" ADD CONSTRAINT "ISSUE_PK" PRIMARY KEY ("ISSUEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
  ALTER TABLE "APPS"."ISSUE" MODIFY ("PARTPRICE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ISSUE" MODIFY ("WORKORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ISSUESTATUS
--------------------------------------------------------

  ALTER TABLE "APPS"."ISSUESTATUS" MODIFY ("ISSUESTATUS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ISSUESTATUS" ADD CONSTRAINT "PK_ISSUESTATUS" PRIMARY KEY ("ISSUESTATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ODP_USER
--------------------------------------------------------

  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USERTITLE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USEREMAIL" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USERIDNUMBER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USERLEVEL" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" MODIFY ("USERSECTION" NOT NULL ENABLE);
  ALTER TABLE "APPS"."ODP_USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PMTEMPLATE
--------------------------------------------------------

  ALTER TABLE "APPS"."PMTEMPLATE" MODIFY ("PMSN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."PMTEMPLATE" ADD CONSTRAINT "PMTEMPLATE_PK" PRIMARY KEY ("PMSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPAREPART
--------------------------------------------------------

  ALTER TABLE "APPS"."SPAREPART" MODIFY ("PARTCODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."SPAREPART" MODIFY ("PARTDIRECTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."SPAREPART" MODIFY ("PARTPRICE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."SPAREPART" MODIFY ("PARTSTOCKQTY" NOT NULL ENABLE);
  ALTER TABLE "APPS"."SPAREPART" ADD CONSTRAINT "PK_SPAREPART" PRIMARY KEY ("PARTCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STORERETURN
--------------------------------------------------------

  ALTER TABLE "APPS"."STORERETURN" MODIFY ("RETURNID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."STORERETURN" MODIFY ("WORKORDER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."STORERETURN" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "APPS"."STORERETURN" MODIFY ("COMPONENTSN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."STORERETURN" MODIFY ("RETURNPRICE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."STORERETURN" ADD CONSTRAINT "STORERETURN_PK" PRIMARY KEY ("RETURNID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UOM
--------------------------------------------------------

  ALTER TABLE "APPS"."UOM" MODIFY ("UOMID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."UOM" ADD CONSTRAINT "PK_UOM" PRIMARY KEY ("UOMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERLEVEL
--------------------------------------------------------

  ALTER TABLE "APPS"."USERLEVEL" MODIFY ("USERLEVEL" NOT NULL ENABLE);
  ALTER TABLE "APPS"."USERLEVEL" ADD CONSTRAINT "PK_USERLEVEL" PRIMARY KEY ("USERLEVEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERSECTION
--------------------------------------------------------

  ALTER TABLE "APPS"."USERSECTION" MODIFY ("USERSECTION" NOT NULL ENABLE);
  ALTER TABLE "APPS"."USERSECTION" ADD CONSTRAINT "PK_USERSECTION" PRIMARY KEY ("USERSECTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKDONETYPES
--------------------------------------------------------

  ALTER TABLE "APPS"."WORKDONETYPES" MODIFY ("WORKDONETYPEID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKDONETYPES" MODIFY ("WORKDONETYPEDIRECTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKDONETYPES" ADD CONSTRAINT "PK_WORKDONETYPES" PRIMARY KEY ("WORKDONETYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKORDER
--------------------------------------------------------

  ALTER TABLE "APPS"."WORKORDER" MODIFY ("WORKORDERID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDER" MODIFY ("WORKORDERDIRECTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDER" MODIFY ("WORKORDERSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDER" MODIFY ("WORKORDERTYPEID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDER" MODIFY ("WORKORDEREQUIPMENTID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDER" MODIFY ("WORKORDERCREATORID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDER" MODIFY ("WORKORDERREGISTERATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDER" ADD CONSTRAINT "WORKORDER_PK" PRIMARY KEY ("WORKORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKORDERSTATUS
--------------------------------------------------------

  ALTER TABLE "APPS"."WORKORDERSTATUS" MODIFY ("WORKORDERSTATUSID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDERSTATUS" ADD CONSTRAINT "PK_WORKORDERSTATUS" PRIMARY KEY ("WORKORDERSTATUSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKORDERTYPE
--------------------------------------------------------

  ALTER TABLE "APPS"."WORKORDERTYPE" MODIFY ("WORKORDERTYPEDIRECTIVE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDERTYPE" MODIFY ("WORKORDERTYPEID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."WORKORDERTYPE" ADD CONSTRAINT "PK_WORKORDERTYPE" PRIMARY KEY ("WORKORDERTYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BREAKDOWN
--------------------------------------------------------

  ALTER TABLE "APPS"."BREAKDOWN" ADD CONSTRAINT "FK_BREAKDOWN_EQUIPMENT" FOREIGN KEY ("EQUIPMENTID")
	  REFERENCES "APPS"."EQUIPMENT" ("EQUIPMENTID") ENABLE;
  ALTER TABLE "APPS"."BREAKDOWN" ADD CONSTRAINT "FK_BREAKDOWN_WORKORDER" FOREIGN KEY ("WORKORDER")
	  REFERENCES "APPS"."WORKORDER" ("WORKORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPONENT
--------------------------------------------------------

  ALTER TABLE "APPS"."COMPONENT" ADD CONSTRAINT "FK_COMPONENT_COMPONENTSTATUS" FOREIGN KEY ("COMPONENTSTATUS")
	  REFERENCES "APPS"."COMPONENTSTATUS" ("COMPONENTSTATUS") ENABLE;
  ALTER TABLE "APPS"."COMPONENT" ADD CONSTRAINT "FK_COMPONENT_SPAREPART" FOREIGN KEY ("COMPONENTPARTCODE")
	  REFERENCES "APPS"."SPAREPART" ("PARTCODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPMENT
--------------------------------------------------------

  ALTER TABLE "APPS"."EQUIPMENT" ADD CONSTRAINT "FK_EQUIPMENT_EQUIPMENTFAMILY" FOREIGN KEY ("EQUIPMENTFAMILYID")
	  REFERENCES "APPS"."EQUIPMENTFAMILY" ("EQUIPMENTFAMILYCODE") ENABLE;
  ALTER TABLE "APPS"."EQUIPMENT" ADD CONSTRAINT "FK_EQUIPMENT_EQUIPMENTSTATUS" FOREIGN KEY ("EQUIPMENTSTATUSID")
	  REFERENCES "APPS"."EQUIPMENTSTATUS" ("EQUIPMENTSTATUSID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FUELINGWORKORDER
--------------------------------------------------------

  ALTER TABLE "APPS"."FUELINGWORKORDER" ADD CONSTRAINT "FK_FUELINGWORKORDER_EQUIPMENT" FOREIGN KEY ("EQUIPMENTID")
	  REFERENCES "APPS"."EQUIPMENT" ("EQUIPMENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISSUE
--------------------------------------------------------

  ALTER TABLE "APPS"."ISSUE" ADD CONSTRAINT "FK_ISSUE_ISSUERID" FOREIGN KEY ("ISSUERID")
	  REFERENCES "APPS"."ODP_USER" ("USERID") ENABLE;
  ALTER TABLE "APPS"."ISSUE" ADD CONSTRAINT "FK_ISSUE_ISSUESTATUS" FOREIGN KEY ("ISSUESTATE")
	  REFERENCES "APPS"."ISSUESTATUS" ("ISSUESTATUS") ENABLE;
  ALTER TABLE "APPS"."ISSUE" ADD CONSTRAINT "FK_ISSUE_REQUESTERID" FOREIGN KEY ("REQUESTERID")
	  REFERENCES "APPS"."ODP_USER" ("USERID") ENABLE;
  ALTER TABLE "APPS"."ISSUE" ADD CONSTRAINT "FK_ISSUE_SPAREPART" FOREIGN KEY ("SPAREPARTCODE")
	  REFERENCES "APPS"."SPAREPART" ("PARTCODE") ENABLE;
  ALTER TABLE "APPS"."ISSUE" ADD CONSTRAINT "FK_ISSUE_WORKORDER" FOREIGN KEY ("WORKORDER")
	  REFERENCES "APPS"."WORKORDER" ("WORKORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ODP_USER
--------------------------------------------------------

  ALTER TABLE "APPS"."ODP_USER" ADD CONSTRAINT "FK_USER_USERLEVEL" FOREIGN KEY ("USERLEVEL")
	  REFERENCES "APPS"."USERLEVEL" ("USERLEVEL") ENABLE;
  ALTER TABLE "APPS"."ODP_USER" ADD CONSTRAINT "FK_USER_USERSECTION" FOREIGN KEY ("USERSECTION")
	  REFERENCES "APPS"."USERSECTION" ("USERSECTION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PMTEMPLATE
--------------------------------------------------------

  ALTER TABLE "APPS"."PMTEMPLATE" ADD CONSTRAINT "FK_PMTEMPLATE_EQUIPMENTFAMILY" FOREIGN KEY ("EQUIPMENTFAMILY")
	  REFERENCES "APPS"."EQUIPMENTFAMILY" ("EQUIPMENTFAMILYCODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPAREPART
--------------------------------------------------------

  ALTER TABLE "APPS"."SPAREPART" ADD CONSTRAINT "FK_SPAREPART_UOM" FOREIGN KEY ("UOM")
	  REFERENCES "APPS"."UOM" ("UOMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STORERETURN
--------------------------------------------------------

  ALTER TABLE "APPS"."STORERETURN" ADD CONSTRAINT "FK_STORERETURN_COMPONENT" FOREIGN KEY ("COMPONENTSN")
	  REFERENCES "APPS"."COMPONENT" ("COMPONENTSN") ENABLE;
  ALTER TABLE "APPS"."STORERETURN" ADD CONSTRAINT "FK_STORERETURN_WORKORDER" FOREIGN KEY ("WORKORDER")
	  REFERENCES "APPS"."WORKORDER" ("WORKORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKORDER
--------------------------------------------------------

  ALTER TABLE "APPS"."WORKORDER" ADD CONSTRAINT "FK_WORKORDER_EQUIPMENT" FOREIGN KEY ("WORKORDEREQUIPMENTID")
	  REFERENCES "APPS"."EQUIPMENT" ("EQUIPMENTID") ENABLE;
  ALTER TABLE "APPS"."WORKORDER" ADD CONSTRAINT "FK_WORKORDER_USER" FOREIGN KEY ("WORKORDERCREATORID")
	  REFERENCES "APPS"."ODP_USER" ("USERID") ENABLE;
  ALTER TABLE "APPS"."WORKORDER" ADD CONSTRAINT "FK_WORKORDER_WORKDONETYPES" FOREIGN KEY ("WORKDONETYPE")
	  REFERENCES "APPS"."WORKDONETYPES" ("WORKDONETYPEID") ENABLE;
  ALTER TABLE "APPS"."WORKORDER" ADD CONSTRAINT "FK_WORKORDER_WORKORDERSTATUS" FOREIGN KEY ("WORKORDERSTATUSID")
	  REFERENCES "APPS"."WORKORDERSTATUS" ("WORKORDERSTATUSID") ENABLE;
  ALTER TABLE "APPS"."WORKORDER" ADD CONSTRAINT "FK_WORKORDER_WORKORDERTYPE" FOREIGN KEY ("WORKORDERTYPEID")
	  REFERENCES "APPS"."WORKORDERTYPE" ("WORKORDERTYPEID") ENABLE;
