//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BREAKDOWN
    {
        public string EQUIPMENTID { get; set; }
        public Nullable<System.DateTime> FROMTIME { get; set; }
        public Nullable<System.DateTime> TOTIME { get; set; }
        public int WORKORDER { get; set; }
        public string BDNREASON { get; set; }
        public int BREAKDOWNID { get; set; }
        public Nullable<decimal> BDNTOTALTIME { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
        public virtual WORKORDER WORKORDER1 { get; set; }
    }
}
