//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class breakDown
    {
        public int id { get; set; }
        public string equipmentID { get; set; }
        public System.TimeSpan fromTime { get; set; }
        public System.TimeSpan toTime { get; set; }
        public Nullable<int> workOrder { get; set; }
        public string bdnReason { get; set; }
    
        public virtual workOrder workOrder1 { get; set; }
    }
}
