//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPONENT()
        {
            this.STORERETURNs = new HashSet<STORERETURN>();
        }
    
        public string COMPONENTSN { get; set; }
        public string COMPONENTPARTCODE { get; set; }
        public string COMPONENTSTATUS { get; set; }
        public string COMPONENTEQUIPMENT { get; set; }
        public string COMPONENTMANFACTURER { get; set; }
        public string COMPONENTMODEL { get; set; }
    
        public virtual COMPONENTSTATU COMPONENTSTATU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORERETURN> STORERETURNs { get; set; }
        public virtual SPAREPART SPAREPART { get; set; }
    }
}
