//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class component
    {
        public string componentSN { get; set; }
        public string componentFamilyID { get; set; }
        public string componentID { get; set; }
        public string componentManufacturer { get; set; }
        public Nullable<int> componentHR { get; set; }
        public string componentStatusID { get; set; }
        public string attachedEquipID { get; set; }
    
        public virtual componentFamilyIDDirective componentFamilyIDDirective { get; set; }
        public virtual componentStatu componentStatu { get; set; }
        public virtual equipment equipment { get; set; }
    }
}
