//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment()
        {
            this.components = new HashSet<component>();
            this.fuelingWorkOrders = new HashSet<fuelingWorkOrder>();
            this.workOrders = new HashSet<workOrder>();
        }
    
        public string equipmentID { get; set; }
        public string equipmentSN { get; set; }
        public int equipmentHR { get; set; }
        public Nullable<System.DateTime> equipmentHRDate { get; set; }
        public string equipmentStatusID { get; set; }
        public string manufacturer { get; set; }
        public string equipmentFamilyID { get; set; }
        public string equipmentDirective { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<component> components { get; set; }
        public virtual equipmentFamily equipmentFamily { get; set; }
        public virtual equipmentStatu equipmentStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fuelingWorkOrder> fuelingWorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workOrder> workOrders { get; set; }
    }
}
