//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPMENT()
        {
            this.FUELINGWORKORDERs = new HashSet<FUELINGWORKORDER>();
            this.WORKORDERs = new HashSet<WORKORDER>();
        }
    
        public string EQUIPMENTID { get; set; }
        public string EQUIPMENTFAMILYID { get; set; }
        public string EQUIPMENTSN { get; set; }
        public int EQUIPMENTHR { get; set; }
        public Nullable<System.DateTime> EQUIPMENTHRDATE { get; set; }
        public string EQUIPMENTSTATUSID { get; set; }
        public string EQUIPMENTENGINESN { get; set; }
        public string EQUIPMENTTRNSN { get; set; }
        public string EQUIPMENTDAXSN { get; set; }
        public string EQUIPMENTSAXSN { get; set; }
        public Nullable<System.DateTime> INSERVICEDATE { get; set; }
        public string EQUIPMENTDIRECTIVE { get; set; }
    
        public virtual COMPONENT COMPONENT { get; set; }
        public virtual COMPONENT COMPONENT1 { get; set; }
        public virtual COMPONENT COMPONENT2 { get; set; }
        public virtual COMPONENT COMPONENT3 { get; set; }
        public virtual EQUIPMENTFAMILY EQUIPMENTFAMILY { get; set; }
        public virtual EQUIPMENTSTATU EQUIPMENTSTATU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUELINGWORKORDER> FUELINGWORKORDERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKORDER> WORKORDERs { get; set; }
    }
}
