//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUELINGWORKORDER
    {
        public int FUELINGWORKORDER1 { get; set; }
        public string EQUIPMENTID { get; set; }
        public int FUELQTY { get; set; }
        public Nullable<int> EQUIPMENTREADING { get; set; }
        public System.DateTime FUELINGDATE { get; set; }
    
        public virtual EQUIPMENT EQUIPMENT { get; set; }
    }
}
