//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuelingWorkOrder
    {
        public int fuelingWorkOrder1 { get; set; }
        public string equipmentID { get; set; }
        public int fuelQty { get; set; }
        public Nullable<int> equipmentReading { get; set; }
        public System.DateTime fuelingDate { get; set; }
    
        public virtual equipment equipment { get; set; }
    }
}
