//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODPEntities_ORACLE : DbContext
    {
        public ODPEntities_ORACLE()
            : base("name=ODPEntities_ORACLE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPONENT> COMPONENTs { get; set; }
        public virtual DbSet<COMPONENTSTATU> COMPONENTSTATUS { get; set; }
        public virtual DbSet<EQUIPMENT> EQUIPMENTs { get; set; }
        public virtual DbSet<EQUIPMENTFAMILY> EQUIPMENTFAMILies { get; set; }
        public virtual DbSet<EQUIPMENTSTATU> EQUIPMENTSTATUS { get; set; }
        public virtual DbSet<FUELINGWORKORDER> FUELINGWORKORDERs { get; set; }
        public virtual DbSet<ISSUESTATU> ISSUESTATUS { get; set; }
        public virtual DbSet<ODP_USER> ODP_USER { get; set; }
        public virtual DbSet<PMTEMPLATE> PMTEMPLATEs { get; set; }
        public virtual DbSet<STORERETURN> STORERETURNs { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<USERLEVEL> USERLEVELs { get; set; }
        public virtual DbSet<USERSECTION> USERSECTIONs { get; set; }
        public virtual DbSet<WORKDONETYPE> WORKDONETYPES { get; set; }
        public virtual DbSet<WORKORDERSTATU> WORKORDERSTATUS { get; set; }
        public virtual DbSet<WORKORDERTYPE> WORKORDERTYPEs { get; set; }
        public virtual DbSet<BREAKDOWN> BREAKDOWNs { get; set; }
        public virtual DbSet<ISSUE> ISSUEs { get; set; }
        public virtual DbSet<SPAREPART> SPAREPARTs { get; set; }
        public virtual DbSet<WORKORDER> WORKORDERs { get; set; }
    }
}
