//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODP_ONHAND_QTY
    {
        public decimal INVENTORY_ITEM_ID { get; set; }
        public decimal ORGANIZATION_ID { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public decimal LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public decimal CREATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
        public decimal PRIMARY_TRANSACTION_QUANTITY { get; set; }
        public string SUBINVENTORY_CODE { get; set; }
        public string REVISION { get; set; }
        public Nullable<decimal> LOCATOR_ID { get; set; }
        public Nullable<decimal> CREATE_TRANSACTION_ID { get; set; }
        public Nullable<decimal> UPDATE_TRANSACTION_ID { get; set; }
        public string LOT_NUMBER { get; set; }
        public Nullable<System.DateTime> ORIG_DATE_RECEIVED { get; set; }
        public Nullable<decimal> COST_GROUP_ID { get; set; }
        public Nullable<decimal> CONTAINERIZED_FLAG { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public Nullable<decimal> TASK_ID { get; set; }
        public decimal ONHAND_QUANTITIES_ID { get; set; }
        public decimal ORGANIZATION_TYPE { get; set; }
        public decimal OWNING_ORGANIZATION_ID { get; set; }
        public decimal OWNING_TP_TYPE { get; set; }
        public decimal PLANNING_ORGANIZATION_ID { get; set; }
        public decimal PLANNING_TP_TYPE { get; set; }
        public string TRANSACTION_UOM_CODE { get; set; }
        public decimal TRANSACTION_QUANTITY { get; set; }
        public string SECONDARY_UOM_CODE { get; set; }
        public Nullable<decimal> SECONDARY_TRANSACTION_QUANTITY { get; set; }
        public decimal IS_CONSIGNED { get; set; }
        public Nullable<decimal> LPN_ID { get; set; }
        public Nullable<decimal> STATUS_ID { get; set; }
        public string MCC_CODE { get; set; }
    }
}
