//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODP_USER
    {
        public string USERNAME { get; set; }
        public string USERID { get; set; }
        public string USERPASSWORD { get; set; }
        public string USERTITLE { get; set; }
        public byte[] USERIMAGE { get; set; }
        public string USEREMAIL { get; set; }
        public int USERIDNUMBER { get; set; }
        public string USERLEVEL { get; set; }
        public string USERSECTION { get; set; }
    }
}
