//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODPEntities_ORACLE : DbContext
    {
        public ODPEntities_ORACLE()
            : base("name=ODPEntities_ORACLE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BREAKDOWN> BREAKDOWNS { get; set; }
        public virtual DbSet<COMPONENT> COMPONENTS { get; set; }
        public virtual DbSet<COMPONENTSTATU> COMPONENTSTATUS { get; set; }
        public virtual DbSet<EQUIPMENT> EQUIPMENTS { get; set; }
        public virtual DbSet<EQUIPMENTFAMILY> EQUIPMENTFAMILIES { get; set; }
        public virtual DbSet<EQUIPMENTSTATU> EQUIPMENTSTATUS { get; set; }
        public virtual DbSet<EQUIPMENTTYPE> EQUIPMENTTYPES { get; set; }
        public virtual DbSet<FUELINGWORKORDER> FUELINGWORKORDERS { get; set; }
        public virtual DbSet<ISSUE> ISSUES { get; set; }
        public virtual DbSet<ISSUESTATU> ISSUESTATUS { get; set; }
        public virtual DbSet<ODP_USER> ODP_USERS { get; set; }
        public virtual DbSet<PMTEMPLATE> PMTEMPLATES { get; set; }
        public virtual DbSet<SPAREPART> SPAREPARTS { get; set; }
        public virtual DbSet<STORERETURN> STORERETURNS { get; set; }
        public virtual DbSet<UOM> UOMS { get; set; }
        public virtual DbSet<USERLEVEL> USERLEVELS { get; set; }
        public virtual DbSet<USERSECTION> USERSECTIONS { get; set; }
        public virtual DbSet<WORKDONETYPE> WORKDONETYPES { get; set; }
        public virtual DbSet<WORKORDER> WORKORDERS { get; set; }
        public virtual DbSet<WORKORDERSTATU> WORKORDERSTATUS { get; set; }
        public virtual DbSet<WORKORDERTYPE> WORKORDERTYPES { get; set; }
        public virtual DbSet<ODP_ONHAND_QTY> ODP_ONHAND_QTY { get; set; }
    }
}
