//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partCode
    {
        public string equipmentFamilyCode { get; set; }
        public string location { get; set; }
        public string component { get; set; }
        public string assembly { get; set; }
        public string partID { get; set; }
        public int partNo { get; set; }
        public string sparePartCode { get; set; }
    }
}
