//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partCode
    {
        public string equipmentID { get; set; }
        public string componentID { get; set; }
        public string systemID { get; set; }
        public string partNumber { get; set; }
        public string partCode1 { get; set; }
    }
}
