//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmTemplate
    {
        public int pmSN { get; set; }
        public string equipmentFamily { get; set; }
        public string pmDirective { get; set; }
        public byte[] pmAttachment { get; set; }
        public Nullable<int> pmIssues { get; set; }
    
        public virtual equipmentFamily equipmentFamily1 { get; set; }
    }
}
