//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMTEMPLATE
    {
        public int PMSN { get; set; }
        public string EQUIPMENTFAMILY { get; set; }
        public string PMDIRECTIVE { get; set; }
        public byte[] PMATTACHMENT { get; set; }
        public Nullable<int> PMISSUES { get; set; }
    
        public virtual EQUIPMENTFAMILY EQUIPMENTFAMILY1 { get; set; }
    }
}
