//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sparePart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sparePart()
        {
            this.issues = new HashSet<issue>();
        }
    
        public string partCode { get; set; }
        public string manufacturerPN { get; set; }
        public string partDirective { get; set; }
        public decimal partPrice { get; set; }
        public int partStockQty { get; set; }
        public string compatableEquipmentFamilyID { get; set; }
        public string supplierID { get; set; }
        public Nullable<int> reservedStock { get; set; }
        public Nullable<int> availableStock { get; set; }
        public string uom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issue> issues { get; set; }
        public virtual uom uom1 { get; set; }
    }
}
