//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD:ODP2/Models/equipmentStatu.cs
    public partial class equipmentStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipmentStatu()
        {
            this.equipments = new HashSet<equipment>();
        }
    
        public string equipmentStatusID { get; set; }
        public string equipmentStatusDirective { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment> equipments { get; set; }
=======
    public partial class uom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uom()
        {
            this.spareParts = new HashSet<sparePart>();
        }
    
        public string uomID { get; set; }
        public string uomDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sparePart> spareParts { get; set; }
>>>>>>> References are cleaned with all Conflicts Solved:ODP2/Models/uom.cs
    }
}
