//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.workOrders = new HashSet<workOrder>();
        }
    
        public string userName { get; set; }
        public string userID { get; set; }
        public string userPassword { get; set; }
        public string userTitle { get; set; }
        public byte[] userImage { get; set; }
        public string userEmail { get; set; }
        public int userIDNumber { get; set; }
        public string userLevel { get; set; }
        public string userSection { get; set; }
    
        public virtual userLevel userLevel1 { get; set; }
        public virtual userSection userSection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workOrder> workOrders { get; set; }
    }
}
