//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workOrder()
        {
            this.breakDowns = new HashSet<breakDown>();
            this.issues = new HashSet<issue>();
        }
    
        public int workOrderID { get; set; }
        public string workOrderDirective { get; set; }
        public string workOrderStatusID { get; set; }
        public string workOrderTypeID { get; set; }
        public Nullable<System.DateTime> workStartDate { get; set; }
        public Nullable<System.DateTime> workDoneDate { get; set; }
        public string workOrderEquipmentID { get; set; }
        public string workOrderCreatorID { get; set; }
        public Nullable<int> workOrderBillOfMaterial { get; set; }
        public System.DateTime workOrderRegisterationDate { get; set; }
        public Nullable<System.DateTime> workOrderFinishDate { get; set; }
        public string workOrderNotes { get; set; }
        public Nullable<int> equipmentRH { get; set; }
        public string workDoneType { get; set; }
        public byte[] workOrderAttach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<breakDown> breakDowns { get; set; }
        public virtual equipment equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issue> issues { get; set; }
        public virtual user user { get; set; }
        public virtual workDoneType workDoneType1 { get; set; }
        public virtual workOrderStatu workOrderStatu { get; set; }
        public virtual workOrderType workOrderType { get; set; }
    }
}
